version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@5'
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install-npm-wee
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
        - run:
            name: test
            command: npm test
        - run:
            name: code-coverage
            command: './node_modules/.bin/nyc report --reporter=text-lcov'
        - store_artifacts:
            path: test-results.xml
            prefix: tests
        - store_artifacts:
            path: coverage
            prefix: coverage
        - store_test_results:
            path: test-results.xml
workflows:
    build-and-test:
      jobs:
        - build-and-test