version: 2.1
jobs:
  build:
    working_directory: ~/simpleProject_docker
    docker:
      - image: lescobar05/simple-project:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_test_results:
          path: test-results.xml